// Mock data for UI development - replace with your API calls
import { Event, Offer, BusinessPartner } from "@shared/schema";

export const mockBusinessPartner: BusinessPartner = {
  id: 1,
  userId: 1,
  firstName: "John",
  lastName: "Doe",
  contactNumber: "9876543210",
  sex: "M",
  dob: "1990-01-01",
  info: "Experienced business partner",
  idNumber: "123456789012",
  idVerified: true,
  isBusiness: true,
  isLost: false,
  currentCity: "Mumbai",
  relationshipStatus: "Single",
  lookingFor: "serious",
  socialInfo: "Active on social media",
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockOffers: Offer[] = [
  {
    id: 1,
    businessPartnerId: 1,
    name: "New Year Special",
    text: "Special discount for new year events",
    percentage: 25,
    startDate: new Date("2025-01-01"),
    expiryDate: new Date("2025-01-31"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    businessPartnerId: 1,
    name: "Valentine's Day Offer",
    text: "Romantic events special discount",
    percentage: 20,
    startDate: new Date("2025-02-01"),
    expiryDate: new Date("2025-02-14"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockEvents: Event[] = [
  {
    id: 1,
    hostId: 1,
    name: "Business Networking Mixer",
    description: "Connect with like-minded business professionals in a relaxed atmosphere.",
    bannerImage: null,
    startDate: new Date("2025-02-15T18:00:00"),
    endDate: new Date("2025-02-15T21:00:00"),
    maxParticipants: 50,
    price: 1500,
    currency: "INR",
    requireIdVerification: true,
    location: "Mumbai Business District",
    draftMode: false,
    status: "active",
    cancellationReason: null,
    cancelledAt: null,
    offerId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    hostId: 1,
    name: "Tech Startup Showcase",
    description: "Showcase your startup ideas and connect with potential investors.",
    bannerImage: null,
    startDate: new Date("2025-03-01T10:00:00"),
    endDate: new Date("2025-03-01T16:00:00"),
    maxParticipants: 100,
    price: 0,
    currency: "INR",
    requireIdVerification: false,
    location: "Bangalore Tech Hub",
    draftMode: false,
    status: "active",
    cancellationReason: null,
    cancelledAt: null,
    offerId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    hostId: 1,
    name: "Photography Workshop",
    description: "Learn advanced photography techniques from industry experts.",
    bannerImage: null,
    startDate: new Date("2025-01-20T09:00:00"),
    endDate: new Date("2025-01-20T17:00:00"),
    maxParticipants: 25,
    price: 2500,
    currency: "INR",
    requireIdVerification: false,
    location: "Delhi Creative Studio",
    draftMode: false,
    status: "active",
    cancellationReason: null,
    cancelledAt: null,
    offerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock analytics data
export const mockAnalytics = {
  totalEvents: 12,
  totalParticipants: 340,
  totalRevenue: 85000,
  upcomingEvents: 5,
  attendanceRate: 87,
  revenueGrowth: 23,
  eventsByMonth: [
    { month: "Jan", events: 2, participants: 65, revenue: 12000 },
    { month: "Feb", events: 3, participants: 89, revenue: 18500 },
    { month: "Mar", events: 2, participants: 45, revenue: 9800 },
    { month: "Apr", events: 4, participants: 102, revenue: 25400 },
    { month: "May", events: 1, participants: 39, revenue: 8300 },
  ],
};